# Generated by Django 5.2 on 2025-04-25 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TattooArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('bio', models.TextField(max_length=600)),
                ('instagram', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('tattoo_picture1', models.ImageField(blank=True, null=True, upload_to='tattoo_pics/')),
                ('tattoo_picture2', models.ImageField(blank=True, null=True, upload_to='tattoo_pics/')),
                ('tattoo_picture3', models.ImageField(blank=True, null=True, upload_to='tattoo_pics/')),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
