# Generated by Django 5.2 on 2025-04-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tattooartist',
            name='style',
            field=models.CharField(choices=[('traditional', 'Traditional'), ('fineline', 'Fineline'), ('realism_color', 'Realism (Color)'), ('realism_blackgrey', 'Realism (Black & Grey)'), ('newschool', 'New School'), ('blackwork', 'Black Work'), ('coverup', 'Cover Up'), ('neotraditional', 'Neo-Traditional')], default='traditional', max_length=50),
        ),
    ]
