# Generated by Django 4.2.7 on 2025-03-24 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TattooStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='tattooartist',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='artist_profiles/'),
        ),
        migrations.AddField(
            model_name='tattooartist',
            name='styles',
            field=models.ManyToManyField(blank=True, to='artists.tattoostyle'),
        ),
    ]
